services:
  sukrtya-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sukrtya-ui
    ports:
      - "3000:3000"
    environment:
      # API endpoint configuration
      - REACT_APP_API_BASE_URL=https://sukrtyavhsndapi.psmri.in
    restart: unless-stopped
